name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt packages
      run: |
           sudo apt update
           sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake qml-module-qtquick-controls
      shell: bash
    - name: Configure
      run: qmake
    - name: Make
      run: make
