name: build-test

on:
  push:
    branches: [ "action_test" ]
  pull_request:
    branches: [ "action_test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with rpi4-appsdk
      run: |
        echo "Branch: ${GITHUB_REF#refs/heads/}"
        echo "Working Dir: $(pwd)"
        ls -Rl $(pwd)/../
        # docker run -v ${PWD}:/work -t joukan/rpi4-appsdk:latest
      shell: bash
    
