name: CI check

on:
  pull_request:
    branches: [ "stable/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with rpi4-appsdk
      run: docker run -v ${PWD}:/work -t joukan/rpi4-appsdk:latest
      shell: bash
    
