name:  Publish Container Image

on:
  push:
    tags:
      - v0.**

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set output
      id: vars
      run:  |
        echo ${GITHUB_REF#refs/*/}
        echo "tag=$(echo ${GITHUB_REF#refs/*/} | sed 's/^v//')"
        echo "tag=$(echo ${GITHUB_REF#refs/*/} | sed 's/^v//')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build with rpi4-appsdk
      run: docker run -v ${PWD}:/work -t joukan/rpi4-appsdk:latest
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/saimizi/homepop/homepop:${{ steps.vars.outputs.tag }}
